version: "3.8"

services:
  backend:
    image: ${IMAGE_PREFIX}backend${IMAGE_TAG}
    build:
      context: backend/blog
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_PREFIX}backend${IMAGE_TAG}
      args:
        - CI_REGISTRY=${CI_REGISTRY}/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/blog:/app:delegated
    ports:
      - "8000:8000"
    environment: # local values
      - ENV=local
