version: "3.8"

services:
  backend:
    image: granthynd/blog_backend${IMAGE_TAG}
    build:
      context: backend/blog
      dockerfile: Dockerfile
      cache_from:
        - granthynd/blog_backend${IMAGE_TAG}
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/blog:/app:delegated
    ports:
      - "8000:8000"
    environment: # local values
      - ENV=local

  frontend:
    image: granthynd/blog_frontend${IMAGE_TAG}
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - granthynd/blog_frontend${IMAGE_TAG}
    volumes:
      - ./frontend:/usr/app:delegated
    ports:
      - "3000:3000"
    environment: # local values
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
