name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_backend
      run: docker build --file backend/blog/Dockerfile ./backend/blog
    - name: build_frontend
      run: docker build --file frontend/Dockerfile ./frontend
