name: Deploy database and application

on:
  workflow_run:
    workflows: ["Build and publish frontend"]
    types: ["completed"]

defaults:
  run:
    shell: bash

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  BACKEND_DOMAIN: ${{ secrets.BACKEND_DOMAIN }}
  FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-helm@v1
        with:
          version: "latest"
      - name: Setup kubeconfig file
        run: |
          echo "${KUBECONFIG}" | base64 --decode > /tmp/kubeconfig
      - name: Deploy Postgres Helm Chart
        run: |
          envsubst < infrastructure/services/postgres/values-override.yaml > values.tmp && \
          mv values.tmp infrastructure/services/postgres/values-override.yaml
          helm upgrade blog-database postgresql --install --wait --atomic \
            --repo https://charts.bitnami.com/bitnami \
            -f infrastructure/services/postgres/values-override.yaml \
            --kubeconfig /tmp/kubeconfig
      - name: Deploy Application Helm Chart
        run: |
          envsubst < infrastructure/services/blog/backend-env-vars.yaml > values.tmp && \
          mv values.tmp infrastructure/services/blog/backend-env-vars.yaml
          helm upgrade blog blog --install --wait --atomic \
            --repo https://granthynd.github.io/helm-charts \
            -f infrastructure/services/blog/backend-env-vars.yaml \
            --kubeconfig /tmp/kubeconfig
