name: Deploy application

on:
  workflow_run:
    workflows: ["Build and publish frontend"]
    types: ["completed"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Substitute env vars
        run: envsubst < infrastructure/services/blog/backend-env-vars.yaml > values.tmp && mv values.tmp infrastructure/services/blog/backend-env-vars.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install blog blog --wait --atomic \
            --repo https://granthynd.github.io/helm-charts \
            -f infrastructure/services/blog/backend-env-vars.yaml
          kubeconfig: "${{ secrets.KUBECONFIG }}"
