name: Deploy application

on:
  # TODO: remove after testing
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Build and publish frontend"]
    types: ["completed"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Substitute env vars
        shell: bash
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          BACKEND_DOMAIN: ${{ secrets.BACKEND_DOMAIN }}
          FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN }}
        run: |
          envsubst < infrastructure/services/blog/backend-env-vars.yaml > values.tmp && /
          mv values.tmp infrastructure/services/blog/backend-env-vars.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install blog blog --wait --atomic \
            --repo https://granthynd.github.io/helm-charts \
            -f infrastructure/services/blog/backend-env-vars.yaml
          kubeconfig: "${{ secrets.KUBECONFIG }}"
