name: Deploy application

on:
  workflow_run:
    workflows: ["Build and publish frontend"]
    types: ["completed"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade blog blog --install --wait --atomic --repo https://granthynd.github.io/helm-charts
          kubeconfig: "${{ secrets.KUBECONFIG }}"
