name: Build, test and publish frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push_to_registry:
    name: Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: frontend
          tags: granthynd/blog_frontend:${{ github.ref }}
